### ISSUE TITLE
Been struggling with async test context so long!

### ISSUE THREAD

**Issue by alextes** [markhildreth/test-context#18]
This library solves it for me, finally 💛. It's even flexible enough where I can easily use it with a struct I was clumsily calling setup and teardown on myself and then just suffering the lack of teardown when a test would fail.

Thanks for a great lib! You're the best.

![welldone2](https://user-images.githubusercontent.com/2011351/227270370-f95d6e02-4144-4734-98a1-4183d2ccb24d.gif)

**Comment by markhildreth** [comment]
@alextes Thanks for the kind words, I'm glad it's been of use!
