### ISSUE TITLE
Automatically impl TestContext for AsyncTestContext

### ISSUE THREAD

**Issue by Shadow53** [markhildreth/test-context#8]
I am putting together a basic PR for this already, but I think it would be nice for an AsyncTestContext to also automatically implement the synchronous form as well, which can easily be done using `futures::executor::block_on`.

The downside of this is that it prevents custom implementations, though I think if it were opted into via a feature flag or attribute macro (the latter would allow opting in per context), it would prove useful.

A related possibility is to have a macro for each method of blocking. Something like `#[test_context::async_to_sync::{futures,tokio,async-std,smol}]`. It could be useful in the cases where the `AsyncTestContext` uses runtime-specific libraries?

I am curious what your thoughts are on this.

**Comment by markhildreth** [comment]
I've merged the pull request, looks good for some simple cases. Is there a reason why you wouldn't want to do as the `README` shows, which is to use this plus the attribute for the runtime? I understand it would be nice to have just a single header on each test, but I'm not sure that's too much to ask.

**Comment by Shadow53** [comment]
I suppose you are right about the more complex cases. I was trying to brainstorm cases where the automatic impl would be unwanted, but you are right: using a specific runtime should just use the async one.
